# pylint: disable=wildcard-import
"""Modern difference-in-differences estimators."""

from moderndid.data import load_ehec, load_mpdta, load_nsw
from moderndid.did.aggte import aggte
from moderndid.did.aggte_obj import AGGTEResult, format_aggte_result
from moderndid.did.att_gt import att_gt
from moderndid.did.compute_aggte import compute_aggte
from moderndid.did.compute_att_gt import ATTgtResult, ComputeATTgtResult, compute_att_gt
from moderndid.did.mboot import mboot
from moderndid.did.multiperiod_obj import (
    MPPretestResult,
    MPResult,
    format_mp_pretest_result,
    format_mp_result,
    mp,
    mp_pretest,
    summary_mp_pretest,
)
from moderndid.did.plots import (
    plot_att_gt,
    plot_did,
    plot_event_study,
)
from moderndid.did.preprocess import DIDData
from moderndid.did.preprocess_did import preprocess_did
from moderndid.didcont import (
    PTEParams,
    _get_first_difference,
    _get_group,
    _get_group_inner,
    _make_balanced_panel,
    avoid_zero_division,
    basis_dimension,
    compute_r_squared,
    is_full_rank,
    matrix_sqrt,
    setup_pte,
    setup_pte_basic,
    setup_pte_cont,
)
from moderndid.didcont.npiv import (
    MultivariateBasis,
    NPIVResult,
    compute_cck_ucb,
    compute_ucb,
    npiv,
    npiv_choose_j,
    npiv_est,
    npiv_j,
    npiv_jhat_max,
    prodspline,
)
from moderndid.didcont.spline import (
    BSpline,
    SplineBase,
)
from moderndid.didhonest import (
    APRCIResult,
    ARPNuisanceCIResult,
    DeltaRMBResult,
    DeltaRMMResult,
    DeltaRMResult,
    DeltaSDBResult,
    DeltaSDMResult,
    DeltaSDResult,
    DeltaSDRMBResult,
    DeltaSDRMMResult,
    DeltaSDRMResult,
    FLCIResult,
    HonestDiDResult,
    OriginalCSResult,
    SensitivityResult,
    affine_variance,
    basis_vector,
    bin_factor,
    compute_arp_ci,
    compute_arp_nuisance_ci,
    compute_bounds,
    compute_conditional_cs_rm,
    compute_conditional_cs_rmb,
    compute_conditional_cs_rmm,
    compute_conditional_cs_sd,
    compute_conditional_cs_sdb,
    compute_conditional_cs_sdm,
    compute_conditional_cs_sdrm,
    compute_conditional_cs_sdrmb,
    compute_conditional_cs_sdrmm,
    compute_delta_sd_lowerbound_m,
    compute_delta_sd_upperbound_m,
    compute_flci,
    compute_identified_set_rm,
    compute_identified_set_rmb,
    compute_identified_set_rmm,
    compute_identified_set_sd,
    compute_identified_set_sdb,
    compute_identified_set_sdm,
    compute_identified_set_sdrm,
    compute_identified_set_sdrmb,
    compute_identified_set_sdrmm,
    compute_least_favorable_cv,
    compute_vlo_vup_dual,
    construct_original_cs,
    create_interactions,
    create_monotonicity_constraint_matrix,
    create_pre_period_constraint_matrix,
    create_second_difference_matrix,
    create_sensitivity_results_rm,
    create_sensitivity_results_sm,
    create_sign_constraint_matrix,
    estimate_lowerbound_m_conditional_test,
    event_study_plot,
    folded_normal_quantile,
    honest_did,
    lee_coefficient,
    lp_conditional_test,
    maximize_bias,
    minimize_variance,
    plot_sensitivity_rm,
    plot_sensitivity_sm,
    selection_matrix,
    test_in_identified_set,
    test_in_identified_set_flci_hybrid,
    test_in_identified_set_lf_hybrid,
    test_in_identified_set_max,
    validate_conformable,
    validate_symmetric_psd,
)
from moderndid.drdid.bootstrap.boot_ipw_rc import wboot_ipw_rc
from moderndid.drdid.bootstrap.boot_mult import mboot_did, mboot_twfep_did
from moderndid.drdid.bootstrap.boot_panel import (
    wboot_dr_tr_panel,
    wboot_drdid_imp_panel,
    wboot_ipw_panel,
    wboot_reg_panel,
    wboot_std_ipw_panel,
    wboot_twfe_panel,
)
from moderndid.drdid.bootstrap.boot_rc import wboot_drdid_rc1, wboot_drdid_rc2
from moderndid.drdid.bootstrap.boot_rc_ipt import wboot_drdid_ipt_rc1, wboot_drdid_ipt_rc2
from moderndid.drdid.bootstrap.boot_reg_rc import wboot_reg_rc
from moderndid.drdid.bootstrap.boot_std_ipw_rc import wboot_std_ipw_rc
from moderndid.drdid.bootstrap.boot_twfe_rc import wboot_twfe_rc
from moderndid.drdid.drdid import drdid
from moderndid.drdid.estimators.drdid_imp_local_rc import drdid_imp_local_rc
from moderndid.drdid.estimators.drdid_imp_panel import drdid_imp_panel
from moderndid.drdid.estimators.drdid_imp_rc import drdid_imp_rc
from moderndid.drdid.estimators.drdid_panel import drdid_panel
from moderndid.drdid.estimators.drdid_rc import drdid_rc
from moderndid.drdid.estimators.drdid_trad_rc import drdid_trad_rc
from moderndid.drdid.estimators.ipw_did_panel import ipw_did_panel
from moderndid.drdid.estimators.ipw_did_rc import ipw_did_rc
from moderndid.drdid.estimators.reg_did_panel import reg_did_panel
from moderndid.drdid.estimators.reg_did_rc import reg_did_rc
from moderndid.drdid.estimators.std_ipw_did_panel import std_ipw_did_panel
from moderndid.drdid.estimators.std_ipw_did_rc import std_ipw_did_rc
from moderndid.drdid.estimators.twfe_did_panel import twfe_did_panel
from moderndid.drdid.estimators.twfe_did_rc import twfe_did_rc
from moderndid.drdid.estimators.wols import wols_panel, wols_rc
from moderndid.drdid.ipwdid import ipwdid
from moderndid.drdid.ordid import ordid
from moderndid.drdid.print import print_did_result
from moderndid.drdid.propensity.aipw_estimators import aipw_did_panel, aipw_did_rc_imp1, aipw_did_rc_imp2
from moderndid.drdid.propensity.ipw_estimators import ipw_rc
from moderndid.drdid.propensity.pscore_ipt import calculate_pscore_ipt
from moderndid.utils import (
    are_varying,
    complete_data,
    convert_panel_time_to_int,
    create_relative_time_indicators,
    datetime_to_int,
    extract_vars_from_formula,
    fill_panel_gaps,
    is_panel_balanced,
    is_repeated_cross_section,
    long_panel,
    make_panel_balanced,
    panel_has_gaps,
    panel_to_cross_section_diff,
    parse_formula,
    prepare_data_for_did,
    unpanel,
    validate_treatment_timing,
    widen_panel,
)

__all__ = [
    "AGGTEResult",
    "APRCIResult",
    "ARPNuisanceCIResult",
    "ATTgtResult",
    "BSpline",
    "ComputeATTgtResult",
    "DIDData",
    "DeltaRMBResult",
    "DeltaRMMResult",
    "DeltaRMResult",
    "DeltaSDBResult",
    "DeltaSDMResult",
    "DeltaSDResult",
    "DeltaSDRMBResult",
    "DeltaSDRMMResult",
    "DeltaSDRMResult",
    "FLCIResult",
    "HonestDiDResult",
    "MPPretestResult",
    "MPResult",
    "MultivariateBasis",
    "NPIVResult",
    "OriginalCSResult",
    "PTEParams",
    "SensitivityResult",
    "SplineBase",
    "_get_first_difference",
    "_get_group",
    "_get_group_inner",
    "_make_balanced_panel",
    "affine_variance",
    "aggte",
    "aipw_did_panel",
    "aipw_did_rc_imp1",
    "aipw_did_rc_imp2",
    "are_varying",
    "att_gt",
    "avoid_zero_division",
    "basis_dimension",
    "basis_vector",
    "bin_factor",
    "calculate_pscore_ipt",
    "complete_data",
    "compute_aggte",
    "compute_arp_ci",
    "compute_arp_nuisance_ci",
    "compute_att_gt",
    "compute_bounds",
    "compute_cck_ucb",
    "compute_conditional_cs_rm",
    "compute_conditional_cs_rmb",
    "compute_conditional_cs_rmm",
    "compute_conditional_cs_sd",
    "compute_conditional_cs_sdb",
    "compute_conditional_cs_sdm",
    "compute_conditional_cs_sdrm",
    "compute_conditional_cs_sdrmb",
    "compute_conditional_cs_sdrmm",
    "compute_delta_sd_lowerbound_m",
    "compute_delta_sd_upperbound_m",
    "compute_flci",
    "compute_identified_set_rm",
    "compute_identified_set_rmb",
    "compute_identified_set_rmm",
    "compute_identified_set_sd",
    "compute_identified_set_sdb",
    "compute_identified_set_sdm",
    "compute_identified_set_sdrm",
    "compute_identified_set_sdrmb",
    "compute_identified_set_sdrmm",
    "compute_least_favorable_cv",
    "compute_r_squared",
    "compute_ucb",
    "compute_vlo_vup_dual",
    "construct_original_cs",
    "convert_panel_time_to_int",
    "create_interactions",
    "create_monotonicity_constraint_matrix",
    "create_pre_period_constraint_matrix",
    "create_relative_time_indicators",
    "create_second_difference_matrix",
    "create_sensitivity_results_rm",
    "create_sensitivity_results_sm",
    "create_sign_constraint_matrix",
    "datetime_to_int",
    "drdid",
    "drdid_imp_local_rc",
    "drdid_imp_panel",
    "drdid_imp_rc",
    "drdid_panel",
    "drdid_rc",
    "drdid_trad_rc",
    "estimate_lowerbound_m_conditional_test",
    "event_study_plot",
    "extract_vars_from_formula",
    "fill_panel_gaps",
    "folded_normal_quantile",
    "format_aggte_result",
    "format_mp_pretest_result",
    "format_mp_result",
    "honest_did",
    "ipw_did_panel",
    "ipw_did_rc",
    "ipw_rc",
    "ipwdid",
    "is_full_rank",
    "is_panel_balanced",
    "is_repeated_cross_section",
    "lee_coefficient",
    "load_ehec",
    "load_mpdta",
    "load_nsw",
    "long_panel",
    "lp_conditional_test",
    "make_panel_balanced",
    "matrix_sqrt",
    "maximize_bias",
    "mboot",
    "mboot_did",
    "mboot_twfep_did",
    "minimize_variance",
    "mp",
    "mp_pretest",
    "npiv",
    "npiv_choose_j",
    "npiv_est",
    "npiv_j",
    "npiv_jhat_max",
    "ordid",
    "panel_has_gaps",
    "panel_to_cross_section_diff",
    "parse_formula",
    "plot_att_gt",
    "plot_did",
    "plot_event_study",
    "plot_sensitivity_rm",
    "plot_sensitivity_sm",
    "prepare_data_for_did",
    "preprocess_did",
    "print_did_result",
    "prodspline",
    "reg_did_panel",
    "reg_did_rc",
    "selection_matrix",
    "setup_pte",
    "setup_pte_basic",
    "setup_pte_cont",
    "std_ipw_did_panel",
    "std_ipw_did_rc",
    "summary_mp_pretest",
    "test_in_identified_set",
    "test_in_identified_set_flci_hybrid",
    "test_in_identified_set_lf_hybrid",
    "test_in_identified_set_max",
    "twfe_did_panel",
    "twfe_did_rc",
    "unpanel",
    "validate_conformable",
    "validate_symmetric_psd",
    "validate_treatment_timing",
    "wboot_dr_tr_panel",
    "wboot_drdid_imp_panel",
    "wboot_drdid_ipt_rc1",
    "wboot_drdid_ipt_rc2",
    "wboot_drdid_rc1",
    "wboot_drdid_rc2",
    "wboot_ipw_panel",
    "wboot_ipw_rc",
    "wboot_reg_panel",
    "wboot_reg_rc",
    "wboot_std_ipw_panel",
    "wboot_std_ipw_rc",
    "wboot_twfe_panel",
    "wboot_twfe_rc",
    "widen_panel",
    "wols_panel",
    "wols_rc",
]
